Repository farcaster-project/farcaster-node, pull requests merged in 2022-11, with the labels that each got.

#742 Refactor: implement strict bus usage and message type
  diagrams/sequencediagram.svg
  diagrams/sequencediagram.txt
  src/bus/ctl.rs
  src/bus/info.rs
  src/bus/mod.rs
  src/bus/p2p.rs
  src/bus/sync.rs
  src/cli/command.rs
  src/client.rs
  src/databased/runtime.rs
  src/event.rs
  src/farcasterd/runtime.rs
  src/farcasterd/syncer_state_machine.rs
  src/farcasterd/trade_state_machine.rs
  src/grpcd/runtime.rs
  src/opts.rs
  src/peerd/runtime.rs
  src/service.rs
  src/swapd/runtime.rs
  src/swapd/swap_state.rs
  src/syncerd/runtime.rs
  src/walletd/mod.rs
  src/walletd/runtime.rs
  src/walletd/state.rs
  tests/cli.rs
  tests/swap.rs
Labels: refactor, farcaster.dev testing

#744 Bugfix: Use refund address for sweeping bitcoin through walletd
  src/walletd/runtime.rs
Labels: reliability

#740 Fix(syncer_client): remove dangerous unwrap in handle tx confs
  src/swapd/syncer_client.rs
Labels: reliability, farcaster.dev testing

#753 Cli: Return exit code 1 on error
  src/bin/swap-cli.rs
Labels: enhancement

#739 Feature: Extend Grpc implementation
  Cargo.lock
  Cargo.toml
  src/bus/bridge.rs
  src/bus/mod.rs
  src/databased/runtime.rs
  src/event.rs
  src/farcasterd/runtime.rs
  src/farcasterd/syncer_state_machine.rs
  src/farcasterd/trade_state_machine.rs
  src/grpcd/proto/farcaster.proto
  src/grpcd/runtime.rs
  src/swapd/runtime.rs
  tests/cfg/fc2.ci.toml
  tests/cfg/fc2.toml
  tests/grpc.rs
Labels: enhancement, farcaster.dev testing

#748 Syncer: Check for dust amount in sweep bitcoin method
  src/syncerd/bitcoin_syncer.rs
Labels: reliability, farcaster.dev testing

#743 Refactor: reunite reveal messages
  diagrams/sequencediagram.svg
  diagrams/sequencediagram.txt
  src/bus/ctl.rs
  src/bus/p2p.rs
  src/farcasterd/runtime.rs
  src/farcasterd/trade_state_machine.rs
  src/peerd/runtime.rs
  src/swapd/runtime.rs
  src/walletd/runtime.rs
  src/walletd/state.rs
Labels: refactor, farcaster.dev testing

#759 Peerd: Use message receipts to confirm receival
  src/bus/ctl.rs
  src/bus/p2p.rs
  src/peerd/runtime.rs
  src/swapd/runtime.rs
  src/swapd/syncer_client.rs
Labels: reliability, farcaster.dev testing

#765 Enforce msg and bus coupling
  src/databased/runtime.rs
  src/event.rs
  src/farcasterd/runtime.rs
  src/farcasterd/syncer_state_machine.rs
  src/farcasterd/trade_state_machine.rs
  src/service.rs
  src/swapd/runtime.rs
Labels: refactor, farcaster.dev testing

#734 Ci: update containers
  .github/workflows/test.yml
  tests/docker-compose.yml
Labels: test

#778 Grpc: Support list offers endpoint
  src/grpcd/proto/farcaster.proto
  src/grpcd/runtime.rs
  tests/grpc.rs
Labels: enhancement

#785 Grpc improve error handling
  src/grpcd/runtime.rs
Labels: refactor

#769 Add richer data to the swap info
  src/bus/info.rs
  src/grpcd/proto/farcaster.proto
  src/grpcd/runtime.rs
  src/swapd/runtime.rs
Labels: enhancement

#770 Database: Add NodeInfo to CheckpointEntry
  src/bus/types.rs
  src/databased/runtime.rs
  src/farcasterd/trade_state_machine.rs
  src/swapd/runtime.rs
Labels: enhancement
