Repository farcaster-project/farcaster-node, pull requests merged in 2022-07, with the labels that each got.

#506 Persist funding address secret key
  src/databased/runtime.rs
  src/rpc/request.rs
Labels: mainnet

#504 Cancel swap
  shell/_swap-cli
  shell/_swap-cli.ps1
  shell/swap-cli.bash
  src/cli/command.rs
  src/cli/opts.rs
  src/farcasterd/runtime.rs
  src/rpc/request.rs
  src/swapd/runtime.rs
  src/swapd/swap_state.rs
  src/swapd/syncer_client.rs
  src/syncerd/bitcoin_syncer.rs
  src/walletd/runtime.rs
  tests/functional-swap.rs
Labels: mainnet

#507 Persist offer history
  src/databased/runtime.rs
  src/rpc/request.rs
Labels: mainnet

#512 Offer history
  shell/_swap-cli
  shell/_swap-cli.ps1
  shell/swap-cli.bash
  src/cli/command.rs
  src/cli/mod.rs
  src/cli/opts.rs
  src/databased/runtime.rs
  src/farcasterd/runtime.rs
  src/rpc/mod.rs
  src/rpc/request.rs
Labels: mainnet

#518 Swap: Allow cancel for alice refundsig before arb lock
  src/swapd/runtime.rs
  src/swapd/swap_state.rs
Labels: enhancement

#517 Cli: Implement sweep address call
  shell/_swap-cli
  shell/_swap-cli.ps1
  shell/swap-cli.bash
  src/cli/command.rs
  src/cli/opts.rs
  src/databased/runtime.rs
  src/farcasterd/runtime.rs
  src/walletd/runtime.rs
Labels: mainnet

#520 Swap: Ensure a checkpoint is only set once and in the correct order
  src/swapd/mod.rs
  src/swapd/runtime.rs
  src/swapd/swap_state.rs
Labels: refactor

#523 Naming: Rename cancel swap to abort swap
  shell/_swap-cli
  shell/_swap-cli.ps1
  shell/swap-cli.bash
  src/cli/command.rs
  src/cli/opts.rs
  src/farcasterd/runtime.rs
  src/rpc/request.rs
  src/swapd/runtime.rs
  src/swapd/swap_state.rs
  tests/functional-swap.rs
Labels: refactor

#521 Fix Checkpoint race condition
  src/swapd/runtime.rs
  src/swapd/syncer_client.rs
  tests/functional-swap.rs
Labels: mainnet

#524 Swap: Add public offer to GetInfo
  src/rpc/request.rs
  src/swapd/runtime.rs
  src/swapd/swap_state.rs
Labels: mainnet

#533 swapd: fee estimate from syncer (electrum)
  doc/sequencediagram.svg
  doc/sequencediagram.txt
  src/swapd/runtime.rs
  src/swapd/syncer_client.rs
  src/syncerd/bitcoin_syncer.rs
  src/syncerd/syncer_state.rs
  src/syncerd/types.rs
  tests/functional.rs
Labels: mainnet

#574 farcaster-swapd-syncer race-free initiation interplay: improve sequence of msgs
  doc/sequencediagram.svg
  doc/sequencediagram.txt
  src/farcasterd/runtime.rs
  src/rpc/request.rs
  src/swapd/runtime.rs
  src/swapd/swap_state.rs
  src/swapd/syncer_client.rs
  src/syncerd/runtime.rs
  src/walletd/runtime.rs
Labels: mainnet

#604 Deps: Use monero-lws crate instead of repo
  Cargo.lock
  Cargo.toml
Labels: dependencies
