Repository farcaster-project/farcaster-node, pull requests merged in 2022-12, with the labels that each got.

#792 Refactor: Improve reliability of peerd connections
  .github/workflows/test.yml
  diagrams/reconnect_sequencediagram.svg
  diagrams/reconnect_sequencediagram.txt
  diagrams/sequencediagram.svg
  diagrams/sequencediagram.txt
  src/bin/peerd.rs
  src/bus/ctl.rs
  src/bus/info.rs
  src/cli/command.rs
  src/cli/opts.rs
  src/event.rs
  src/farcasterd/runtime.rs
  src/farcasterd/trade_state_machine.rs
  src/grpcd/proto/farcaster.proto
  src/grpcd/runtime.rs
  src/peerd/mod.rs
  src/peerd/runtime.rs
  src/service.rs
  src/swapd/runtime.rs
  src/walletd/runtime.rs
  tests/cli.rs
  tests/grpc.rs
  tests/swap.rs
  tests/utils/fc.rs
Labels: refactor, reliability, farcaster.dev testing

#761 Add richer data to the progress messages
  src/bus/info.rs
  src/bus/types.rs
  src/databased/runtime.rs
  src/farcasterd/runtime.rs
  src/farcasterd/stats.rs
  src/farcasterd/trade_state_machine.rs
  src/grpcd/proto/farcaster.proto
  src/grpcd/runtime.rs
  src/service.rs
  src/swapd/mod.rs
  src/swapd/runtime.rs
  src/swapd/state_report.rs
  src/swapd/swap_state.rs
  src/swapd/syncer_client.rs
  src/swapd/temporal_safety.rs
  src/walletd/runtime.rs
  tests/swap.rs
Labels: enhancement

#786 Swapd: Simplify checkpoint encoding
  src/swapd/runtime.rs
Labels: refactor

#783 Swapd: Some patches and improvements
  src/swapd/runtime.rs
  src/syncerd/monero_syncer.rs
Labels: reliability, bugfix

#779 Farcaster: Cleanup dangling swap info on restart
  src/bus/ctl.rs
  src/databased/runtime.rs
  src/farcasterd/runtime.rs
Labels: enhancement, reliability

#782 Database: Change secret key encoding
  src/bus/types.rs
  src/cli/command.rs
  src/databased/runtime.rs
  src/error.rs
  src/grpcd/runtime.rs
  src/walletd/runtime.rs
Labels: refactor

#755 Cli: Implement endpoint for checking syncer health
  src/bus/ctl.rs
  src/bus/types.rs
  src/cli/command.rs
  src/cli/opts.rs
  src/farcasterd/runtime.rs
  src/farcasterd/syncer_state_machine.rs
  src/grpcd/proto/farcaster.proto
  src/grpcd/runtime.rs
  src/swapd/runtime.rs
  src/syncerd/bitcoin_syncer.rs
  src/syncerd/monero_syncer.rs
  src/syncerd/syncer_state.rs
  src/syncerd/types.rs
Labels: enhancement, farcaster.dev testing

#773 Auto-restore checkpoint on startup
  farcasterd.toml
  src/cli/command.rs
  src/cli/opts.rs
  src/config.rs
  src/farcasterd/runtime.rs
  src/grpcd/proto/farcaster.proto
  src/grpcd/runtime.rs
  tests/cfg/fc1.ci.toml
  tests/cfg/fc1.toml
  tests/cfg/fc2.ci.toml
  tests/cfg/fc2.toml
  tests/grpc.rs
Labels: enhancement, farcaster.dev testing

#790 Busses: Remove transcoders from bridge bus senders
  src/grpcd/runtime.rs
  src/syncerd/bitcoin_syncer.rs
  src/syncerd/monero_syncer.rs
Labels: refactor

#764 Cli: Implement endpoint for listing funding addresses
  src/bus/info.rs
  src/cli/command.rs
  src/cli/opts.rs
  src/databased/runtime.rs
  src/grpcd/proto/farcaster.proto
  src/grpcd/runtime.rs
Labels: enhancement

#766 Config: Define global static bind address
  compose/docker-compose.yml
  compose/farcasterd.toml
  farcasterd.toml
  src/bus/ctl.rs
  src/cli/command.rs
  src/cli/opts.rs
  src/config.rs
  src/farcasterd/trade_state_machine.rs
  src/grpcd/proto/farcaster.proto
  src/grpcd/runtime.rs
  tests/cfg/fc1.ci.toml
  tests/cfg/fc1.toml
  tests/cfg/fc2.ci.toml
  tests/cfg/fc2.toml
  tests/cli.rs
  tests/grpc.rs
  tests/swap.rs
Labels: refactor

#796 Farcaster: Handle take offer failure
  src/bus/p2p.rs
  src/farcasterd/runtime.rs
  src/swapd/runtime.rs
Labels: farcaster.dev testing, API breaking

#789 Swap wallet
  diagrams/sequencediagram.svg
  diagrams/sequencediagram.txt
  diagrams/staterecovery_sequencediagram.svg
  diagrams/staterecovery_sequencediagram.txt
  src/bus/ctl.rs
  src/cli/command.rs
  src/databased/runtime.rs
  src/farcasterd/runtime.rs
  src/farcasterd/trade_state_machine.rs
  src/grpcd/runtime.rs
  src/service.rs
  src/swapd/mod.rs
  src/swapd/runtime.rs
  src/swapd/swap_state.rs
  src/swapd/syncer_client.rs
  src/swapd/wallet.rs
  src/walletd/mod.rs
  src/walletd/runtime.rs
  src/walletd/state.rs
Labels: refactor, farcaster.dev testing

#784 Feat: Use creation height when sweeping Monero
  src/cli/command.rs
  src/farcasterd/syncer_state_machine.rs
  src/grpcd/runtime.rs
  src/swapd/runtime.rs
  src/swapd/syncer_client.rs
  src/swapd/wallet.rs
  src/syncerd/monero_syncer.rs
  src/syncerd/syncer_state.rs
  src/syncerd/types.rs
  tests/bitcoin.rs
  tests/monero.rs
Labels: reliability

#774 Syncer: Implement logic for balance retrieval
  src/bus/ctl.rs
  src/bus/info.rs
  src/bus/types.rs
  src/cli/command.rs
  src/cli/opts.rs
  src/farcasterd/runtime.rs
  src/farcasterd/syncer_state_machine.rs
  src/swapd/runtime.rs
  src/syncerd/bitcoin_syncer.rs
  src/syncerd/monero_syncer.rs
  src/syncerd/types.rs
  tests/bitcoin.rs
  tests/monero.rs
  tests/utils/assert.rs
Labels: enhancement

#838 remove swapd.runtime.syncer_state.{bitcoin,monero}_amount
  src/swapd/runtime.rs
  src/swapd/swap_state.rs
  src/swapd/syncer_client.rs
Labels: refactor

#836 Deps: Update core to v0.6
  .github/workflows/test.yml
  Cargo.lock
  Cargo.toml
  README.md
  diagrams/sequencediagram.svg
  diagrams/sequencediagram.txt
  src/bus/ctl.rs
  src/bus/info.rs
  src/bus/p2p.rs
  src/bus/types.rs
  src/cli/command.rs
  src/cli/mod.rs
  src/cli/opts.rs
  src/databased/runtime.rs
  src/error.rs
  src/event.rs
  src/farcasterd/runtime.rs
  src/farcasterd/trade_state_machine.rs
  src/grpcd/proto/farcaster.proto
  src/grpcd/runtime.rs
  src/swapd/opts.rs
  src/swapd/runtime.rs
  src/swapd/swap_state.rs
  src/swapd/wallet.rs
  src/walletd/runtime.rs
  tests/cli.rs
  tests/grpc.rs
  tests/swap.rs
Labels: dependencies, refactor

#839 Swapd: state refactors
  src/swapd/swap_state.rs
  src/swapd/syncer_client.rs
  src/swapd/wallet.rs
Labels: refactor

#850 Swapd: Logging improvements
  src/swapd/runtime.rs
  src/swapd/swap_state.rs
Labels: refactor

#849 Deps: Run cargo update
  Cargo.lock
Labels: dependencies

#841 Bob verifies Alice's Reveal eagerly
  src/swapd/runtime.rs
  src/swapd/swap_state.rs
  src/swapd/syncer_client.rs
  src/swapd/wallet.rs
Labels: farcaster.dev testing

#859 Syncer health patch
  src/farcasterd/runtime.rs
  src/farcasterd/syncer_state_machine.rs
Labels: bugfix

#844 Swap state: Don't emit Bob aborted swap message twice
  src/swapd/swap_state.rs
Labels: farcaster.dev testing

#831 Syncer State Machine: Handle Task Aborted
  src/farcasterd/runtime.rs
  src/farcasterd/syncer_state_machine.rs
Labels: farcaster.dev testing, bugfix

#852 Deal or No Deal?
  src/cli/command.rs
Labels: enhancement

#865 Swapd: Handle re-orgs and possible mempool drops of broadcasted txs.
  src/swapd/runtime.rs
  src/swapd/swap_state.rs
  src/swapd/syncer_client.rs
Labels: reliability

#871 Grpc: Add deal suffix to selector
  src/grpcd/proto/farcaster.proto
  src/grpcd/runtime.rs
  tests/grpc.rs
Labels: refactor

#872 Grpc: Handle handler drops (usually on client disconnect)
  src/grpcd/runtime.rs
Labels: bugfix

#851 Database: Cleanup Open Deals as well on CleanDanglingDeals
  src/databased/runtime.rs
Labels: bugfix

#861 Feature: Add and consume trade role and status in deal history
  src/bus/ctl.rs
  src/bus/info.rs
  src/bus/types.rs
  src/databased/runtime.rs
  src/farcasterd/runtime.rs
  src/farcasterd/trade_state_machine.rs
  src/grpcd/proto/farcaster.proto
  src/grpcd/runtime.rs
  tests/grpc.rs
Labels: enhancement

#874 Syncer(monero): Disregard unlock time transactions
  src/syncerd/monero_syncer.rs
Labels: security

#873 Syncer: Lower the time spent sleeping on the syncer receiver
  src/syncerd/bitcoin_syncer.rs
  src/syncerd/monero_syncer.rs
Labels: refactor

#870 Swapd: Refactor retrieving txs in syncer client
  src/swapd/runtime.rs
  src/swapd/swap_state.rs
  src/swapd/syncer_client.rs
Labels: refactor

#864 Errors: Wrap error types in Error enum instead of converting to Farcaster::Error
  src/bus/info.rs
  src/config.rs
  src/error.rs
  src/grpcd/runtime.rs
  src/swapd/wallet.rs
  src/syncerd/bitcoin_syncer.rs
Labels: refactor

#866 Syncer: Some Refactors for better logging and ergonomics
  src/farcasterd/syncer_state_machine.rs
  src/swapd/runtime.rs
  src/swapd/swap_state.rs
  src/swapd/syncer_client.rs
  src/syncerd/bitcoin_syncer.rs
  src/syncerd/monero_syncer.rs
  src/syncerd/syncer_state.rs
  src/syncerd/types.rs
  tests/bitcoin.rs
  tests/monero.rs
  tests/utils/assert.rs
Labels: refactor

#878 Cli: health check ignore local by default
  src/bus/types.rs
  src/cli/command.rs
  src/cli/opts.rs
Labels: enhancement

#877 Make clippy annoying again
  .github/workflows/binaries.yml
  .github/workflows/static-analysis.yml
  src/config.rs
  src/databased/runtime.rs
  src/farcasterd/runtime.rs
  src/grpcd/runtime.rs
  src/swapd/runtime.rs
  src/swapd/syncer_client.rs
  src/syncerd/bitcoin_syncer.rs
  src/syncerd/monero_syncer.rs
  src/syncerd/syncer_state.rs
  tests/bitcoin.rs
  tests/grpc.rs
  tests/large_tx_serialization.rs
  tests/monero.rs
  tests/swap.rs
  tests/tooling.rs
  tests/utils/config.rs
  tests/utils/fc.rs
  tests/utils/misc.rs
Labels: test, refactor

#883 Grpcd: Add helper function for executing health check
  src/grpcd/runtime.rs
Labels: refactor

#884 Logs: move syncer state transitions logs to debug level
  src/event.rs
  src/farcasterd/syncer_state_machine.rs
Labels: refactor

#879 Swapd: Use transaction directly from transaction confirmations
  src/swapd/swap_state.rs
Labels: refactor, reliability

#881 Swapd: Cache all transaction related syncer events
  src/swapd/runtime.rs
  src/swapd/swap_state.rs
  src/swapd/syncer_client.rs
Labels: refactor, reliability

#842 If punish only end when punish final, and Bob check punish too
  src/swapd/runtime.rs
  src/swapd/swap_state.rs
  src/swapd/syncer_client.rs
  src/swapd/temporal_safety.rs
  src/swapd/wallet.rs
  src/syncerd/bitcoin_syncer.rs
  src/syncerd/syncer_state.rs
  src/syncerd/types.rs
  tests/bitcoin.rs
  tests/swap.rs
Labels: farcaster.dev testing

#882 Swapd: Complete swap key manager refactor
  src/swapd/mod.rs
  src/swapd/runtime.rs
  src/swapd/swap_key_manager.rs
  src/swapd/swap_state.rs
  src/swapd/syncer_client.rs
  src/swapd/wallet.rs
Labels: refactor, reliability

#885 Refactor: complete temp safety renaming and cleaning
  src/swapd/runtime.rs
  src/swapd/state_report.rs
  src/swapd/swap_state.rs
  src/swapd/temporal_safety.rs
Labels: enhancement, refactor

#887 Swapd: Always abort all tasks on swap end
  src/swapd/runtime.rs
  src/swapd/swap_state.rs
Labels: bugfix

#892 Swap: Move transactions from Runtime to State machine
  src/swapd/runtime.rs
  src/swapd/swap_key_manager.rs
  src/swapd/swap_state.rs
  src/swapd/syncer_client.rs
Labels: refactor

#893 Swap: Move AccLockHeight from Runtime to State
  src/bus/types.rs
  src/cli/command.rs
  src/databased/runtime.rs
  src/grpcd/runtime.rs
  src/swapd/runtime.rs
  src/swapd/swap_key_manager.rs
  src/swapd/swap_state.rs
  src/syncerd/monero_syncer.rs
  tests/monero.rs
Labels: refactor

#894 Core: update to version 0.6.2
  Cargo.lock
  src/cli/opts.rs
  src/grpcd/runtime.rs
  tests/cli.rs
  tests/grpc.rs
  tests/swap.rs
Labels: enhancement, core, dependencies

#896 Swap: Add swap logging to syncer client
  src/swapd/mod.rs
  src/swapd/runtime.rs
  src/swapd/swap_key_manager.rs
  src/swapd/swap_state.rs
  src/swapd/syncer_client.rs
Labels: refactor

#897 Docs: Update diagrams
  diagrams/sequencediagram.svg
  diagrams/sequencediagram.txt
  diagrams/swap_state_machine.svg
  diagrams/swap_state_machine.txt
Labels: documentation

#898 Docs: resync with latest doc version
  docs/Home.md
  docs/Usage.md
  docs/Using-Docker.md
Labels: documentation

#903 Swapd: Don't add color coding to progress message
  src/swapd/swap_key_manager.rs
Labels: bugfix

#906 Swapd: Simplify key manager encoding
  Cargo.lock
  src/swapd/swap_key_manager.rs
Labels: refactor

#908 Swapd: Simplify commitment creation
  src/swapd/runtime.rs
  src/swapd/swap_key_manager.rs
  src/swapd/swap_state.rs
Labels: refactor

#911 Doc: Update diagram description
  diagrams/README.md
  diagrams/node-buses.svg
  diagrams/node-busses.excalidraw
  diagrams/node-busses.svg
Labels: documentation

#913 Swapd: Some simple refactors
  src/swapd/runtime.rs
  src/swapd/swap_key_manager.rs
  src/swapd/swap_state.rs
Labels: refactor
