Repository farcaster-project/farcaster-node, pull requests merged in 2023-01, with the labels that each got.

#910 Feat: cli enhancement and improved deal validation
  farcasterd.toml
  src/cli/command.rs
  src/config.rs
  src/farcasterd/trade_state_machine.rs
  src/grpcd/runtime.rs
Labels: enhancement, refactor

#926 Fix(state report): accordant lock used arbitrating params
  src/swapd/state_report.rs
Labels: bugfix

#925 Fix(tsm): swaps restoring
  src/farcasterd/runtime.rs
  src/farcasterd/trade_state_machine.rs
Labels: farcaster.dev testing, bugfix

#935 Swapd: Retry tx broadcast
  src/swapd/runtime.rs
  src/swapd/swap_state.rs
  src/swapd/syncer_client.rs
Labels: farcaster.dev testing

#937 deal validation: only validate amount of outbound asset
  src/config.rs
  src/farcasterd/trade_state_machine.rs
Labels: farcaster.dev testing
